import type { Channel } from "./types";

/** Ordered to match OpenClaw CHAT_CHANNEL_ORDER. */
export const defaultChannels: Channel[] = [
  {
    type: "telegram",
    name: "Telegram",
    description: "Connect your Telegram bot",
    icon: "📱",
    isEditable: true,
    isConfigured: false,
    isEnabled: false,
    config: null,
  },
  {
    type: "whatsapp",
    name: "WhatsApp",
    description: "Connect to WhatsApp",
    icon: "💬",
    isEditable: false,
    isConfigured: false,
    isEnabled: false,
    config: null,
  },
  {
    type: "discord",
    name: "Discord",
    description: "Connect your Discord bot",
    icon: "🎮",
    isEditable: true,
    isConfigured: false,
    isEnabled: false,
    config: null,
  },
  {
    type: "irc",
    name: "IRC",
    description: "Connect to IRC networks",
    icon: "🌐",
    isEditable: false,
    isConfigured: false,
    isEnabled: false,
    config: null,
  },
  {
    type: "googlechat",
    name: "Google Chat",
    description: "Connect Google Workspace Chat",
    icon: "💬",
    isEditable: false,
    isConfigured: false,
    isEnabled: false,
    config: null,
  },
  {
    type: "slack",
    name: "Slack",
    description: "Connect your Slack workspace",
    icon: "💼",
    isEditable: false,
    isConfigured: false,
    isEnabled: false,
    config: null,
  },
  {
    type: "signal",
    name: "Signal",
    description: "Connect to Signal",
    icon: "🔒",
    isEditable: false,
    isConfigured: false,
    isEnabled: false,
    config: null,
  },
  {
    type: "imessage",
    name: "iMessage",
    description: "Connect to iMessage",
    icon: "💬",
    isEditable: false,
    isConfigured: false,
    isEnabled: false,
    config: null,
  },
];
